Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > Patch Set 1: Code-Review+1
> > 
> > This is needed.  However, there are still issues when I run the drools-apps CSIT:
> > 
> > docker/csit/config/drools-apps/custom/features.pre.sh: change "bash" to "sh"
> > 
> > DeployXacmlPolicies :: Deploys the Policies to Xacml                  | FAIL |
> > IOError: [Errno 2] No such file or directory: '/home/jh7358/docker/csit/deploy.xacml.policies.json'
> > ------------------------------------------------------------------------------
> > DeployDroolsPolicies :: Deploys the Policies to Drools                | FAIL |
> > IOError: [Errno 2] No such file or directory: '/home/jh7358/docker/csit/deploy.drools.policies.json'
> 
> ok for changing to sh
> 
> for those json files originally under scripts/policy/drools-apps in csit repo, where should we relocate? move to csit/config/drools-apps in docker repo?

or move to drools-apps repo?

Patch-set: 1